#[derive(Serialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Category {
    ArtEvent,
    BookEvent,
    MovieEvent,
    Fundraiser,
    Volunteering,
    FamilyEvent,
    FestivalEvent,
    Neighborhood,
    ReligiousEvent,
    Shopping,
    ComedyEvent,
    MusicEvent,
    DanceEvent,
    Nightlife,
    TheaterEvent,
    DiningEvent,
    FoodTasting,
    ConferenceEvent,
    Meetup,
    ClassEvent,
    Lecture,
    Workshop,
    Fitness,
    SportsEvent,
    Other,
}
